#!/bin/bash          
echo "Updating instance"

# run sudo update
sudo yum -y update

echo "installing mosquitto"
sudo wget -O /etc/yum.repos.d/mqtt.repo http://download.opensuse.org/repositories/home:/oojah:/mqtt/RedHat_RHEL-7/home:oojah:mqtt.repo
sudo yum -y install mosquitto mosquitto-clients

echo "installing rabbit mq"
wget https://www.rabbitmq.com/releases/rabbitmq-server/v3.5.7/rabbitmq-server-3.5.7-1.noarch.rpm
sudo yum -y install rabbitmq-server-3.5.7-1.noarch.rpm 
rm rabbitmq-server-3.5.7-1.noarch.rpm
.
